---
- name: execute install script
  hosts: all
  vars:
   - patch_num: RHBA-2014:0718 
   - channelLabel: rhel-x86_64-server
  tasks:
   - name: call
     script: 
       cmd: suse.py "{{patch_num}}" "{{channelLabel}}"
     register: opt
   - debug: 
       msg: "{{opt}}"
