---
- name: Check port 1234 
  hosts: all 
  tasks:
   - name: Wait for port 1234 to become open on the host, don't start checking for 5 seconds, and timeout in 10 seconds
     wait_for:
      port: 1234
      delay: 5
      timeout: 10
